---
title: "Overview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course overview

### Time slots

8 x 1.5h:

- Do 23.02. 
    - 16:00 - 17:30 Uhr 
- Fr 24.02. 
    - 9:00 - 10:30 Uhr 
    - 11:00 - 12:30 Uhr
    - 14:00 - 15:30 Uhr
    - 16:00 - 17:30 Uhr
- Sa 25.02.
    - 9:00 - 10:30 Uhr
    - 11:00 - 12:30 Uhr
    - 13:30 - 15:00 Uhr

### Topics

1. Stunde - R Grundlagen
    1. Installation R + RStudio
    2. R Grundlagen
        1. Grundrechenarten
        2. Gängige Datentypen: Vektoren, Listen, Matrix, Dataframe
        3. if, for
        4. Apply-Familie
        5. Funktionen
        6. Error handling
    3. Bibliotheken
2. Stunde - Dateninspektion
    1. Datensatz betrachten
    2. Daten putzen
    3. Daten plotten
3. Stunde - Regression
    1. Korrelation
    2. Regression: Lineare Modellierung
4. Stunde - Gruppenvergleiche und Klassifizierung
    1. Gruppenvergleiche: Chi2, t-Test
    2. Klassifikation: Supervised Machine learning (Random Forest, kNN)
    3. Machine-learning Zyklus (train-test)
5. Stunde - Lernen ohne Vorwissen (unsupervised learning)
    1. Unsupervised Machine learning (PCA)
    2. Clustering (k-Means, HCA)
6. Stunde
    1. Shiny
7. Stunde
    1. Shiny
8. Stunde
    1. Shiny
    2. Wie geht es weiter?


